services:
  cortec:
    build: .
    image: cortec:latest
    container_name: cortec
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - cortec-network
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb:11
    container_name: cortec_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: cortec
      MYSQL_USER: cortec
      MYSQL_PASSWORD: cortec
      MYSQL_ROOT_PASSWORD: cortec
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - cortec-network

  selenium:
    image: selenium/standalone-chrome
    container_name: cortec_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - cortec-network
    shm_size: 2gb

  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: cortec_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      cortec-network:
        aliases:
          - auth.local

networks:
  cortec-network:

volumes:
  mariadb_data:

